default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: community_blog_development
  username: postgres
  password: 1234
  host: localhost

test:
  <<: *default
  database: community_blog_test
  username: postgres
  password: 1234
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
